import { Post } from "../types/post";

export const posts: Post[] = [
  {
    id: 1,
    img: "/imgs/nature/nature1.jpg",
    label: "Nature 1",
    text: "Some nature 1 text description",
    like: false,
    category: "nature",
  },
  {
    id: 2,
    img: "/imgs/nature/nature2.jpg",
    label: "Nature 1",
    text: "Some nature 2 text description",
    like: false,
    category: "nature",
  },
  {
    id: 3,
    img: "/imgs/nature/nature3.jpg",
    label: "Nature 1",
    text: "Some nature 3 text description",
    like: false,
    category: "nature",
  },

  {
    id: 4,
    img: "/imgs/sport/sport1.jpg",
    label: "Sport 1",
    text: "Some sport 1 text description",
    like: false,
    category: "sport",
  },
  {
    id: 5,
    img: "/imgs/sport/sport2.jpg",
    label: "Sport 1",
    text: "Some sport 2 text description",
    like: false,
    category: "sport",
  },
  {
    id: 6,
    img: "/imgs/sport/sport3.jpg",
    label: "Sport 1",
    text: "Some sport 3 text description",
    like: false,
    category: "sport",
  },

  {
    id: 7,
    img: "/imgs/space/space1.jpg",
    label: "Space 1",
    text: "Some space 1 text description",
    like: false,
    category: "space",
  },
  {
    id: 8,
    img: "/imgs/space/space2.jpg",
    label: "Space 2",
    text: "Some space 2 text description",
    like: false,
    category: "space",
  },
  {
    id: 9,
    img: "/imgs/space/space3.jpg",
    label: "Space 2",
    text: "Some space 3 text description",
    like: false,
    category: "space",
  },

  {
    id: 10,
    img: "/imgs/tech/tech1.jpg",
    label: "Tech 1",
    text: "Some tech 1 text description",
    like: false,
    category: "tech",
  },
  {
    id: 11,
    img: "/imgs/tech/tech2.jpg",
    label: "Tech 2",
    text: "Some tech 2 text description",
    like: false,
    category: "tech",
  },
  {
    id: 12,
    img: "/imgs/tech/tech3.jpg",
    label: "Tech 3",
    text: "Some tech 3 text description",
    like: false,
    category: "tech",
  },
  {
    id: 13,
    img: "/imgs/tech/tech4.jpg",
    label: "Tech 4",
    text: "Some tech 4 text description",
    like: false,
    category: "tech",
  },
];
